version: '3'

services:
    db:
      image: mysql:8.0
      container_name: db_dev
      restart: always
      volumes:
       - ./mysql-data:/var/lib/mysql
      environment:
       MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
       MYSQL_DATABASE: '${DB_NAME}'
      expose:
       - "${DB_PORT}"

    PMA:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: db_pma
      restart: always
      ports:
       - '${PHPMYADMIN_PORT}:80'
      environment:
        PMA_HOST: db